### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by JuhQ** [kasimiraula/BikeAssistant#1]
Backend koodi näyttää tosi hyvältä ja hyvin stukturoidulta. Tässä muutamia huomioita jotka iski silmään.

index.js:ssä on require komentoja keskellä tiedostoa, hyvä käytäntö olisi että kaikki requiret olisi aina tiedoston alussa.
utils/comparator.js tiedostossa olisi muutamissa funktioissa voinut foreachin sijaan käyttää map ja reduce funktioita, tähän tapaan vaikka:
```
const read_attributes = (answers) =>
  answers.map(a => a.attribute)
```

```
const format_bikes_for_comparison = (bikes, attributes) =>
  bikes.reduce((initial, bike) => ({
    ...initial,
    [bike.model]: attributes.map(value => bike.attributes[value])
  }), {})
```

Hienoa että comparatorille on kirjoitettu testit! Tämä helpottaa koodin refaktorointia ja regressiotestausta :)
Testin jsonin rakenne näyttää vähän hassulta, käytän itse json pretty print plugaria jolla jsonin saa formatoitua nätimmäksi: https://github.com/dzhibas/SublimePrettyJson

controllers/results.js tiedostossa on `validate_params` niminen funktio joka ei näytä oikein tekevän mitään
Saman results.js tiedoston `formatAnswer` funktio sisältää mielestäni turhan null tsekkauksen, sen ei pitäisi koskaan saada nullia, vaan arrayn alkion. Tosin tietty jos alkion arvo on null...
Joissain kohdin koodia muuttujia on nimetty vähän hassusti, kannattaa aina suosia luettavuutta koodin lyhyyden edellä. Esim `ans` muuttuja mielummin `answer`, tällöin mahdollisen lukijan ei tarvitse pohtia mitä kyseisellä muuttujalla tarkoitetaan, vaan voi lukea koodia sujuvasti.

Sivuston käytettävyydestä:

Pidän sivuston ulkoasusta, se on selkeä ja toimii.
Olisi kuitenkin hyvä että klikattavat elementit käyttäytyisi kuin klikattavat elementit, eli kyselyiden vaihtoehdoissa olisi kiva nähdä käsikursori, sen saa css määrityksellä: `cursor: pointer;`
Kun saan kyselyn tuloksen ja avaan pyöräsivun, olisi kiva että takaisin tullessa päädyn samalle sivulle/tulokseen. Tämä tosin vaatii joko localstorageen tai backendiin tiedon tallentamista. Ehkä idea tulevaisuutta varten?

### Huom

En löytänyt frontend koodin repositorya, katselmoin fronttikoodin kunhan saan linkin siihen ja lisään katselmoinnin kommenttina tähän issueen

**Comment by kasimiraula** [comment]
Kiitos kommenteista. Requiret oli unohtunut routereiden määrittelyiden eteen, mutta hyvä kun nostit asian esille, niin tulee jatkossa kiinnitettyä enemmän huomiota.

Foreachit on rumia ja hitaita, mutta valitettavasti map reducen käyttö on paikoitellen vielä vähän ontuvaa, niin tein tähän yksinkertaisen toimivan ratkaisun (myös huomioiden datan määrän).

Ylimääräinen `validate_params` oli ajatus parametrien validoinnista, mutta tämän projektin kohdalla mitään fataalia tuskin pääsee tapahtumaan, vaikka validointi puuttuukin :)

Pohtimasi null tarkistus tehdään, jottei `formatAnswer` palauta `undefined`. Näin tapahtuu kaikille kysymyksien vastauksille, jotka on skipattu. Nullin palautus taas helpottaa vastausten myöhempää analysointia.

Muuttujien laiskasti nimeämiseen ei ole selitystä; vain anteeksipyydettävää.

Kiitos `cursos:pointer;` neuvosta – otin sen heti käyttöön.

Pohdin localstoragen käyttöä aiemmin, mutta hylkäsin sen jostain syystä, sillä se ei sopinut sen hetkiseen ajatukseeni. On totta, että olisi mukavaa päästä tarkastelemaan useampaa mallia ilman, että kyselyyn täytyy vastata useampaan kertaan. Eräs vaihtoehto olisi avata pyöräsivu uudessa ikkunassa.
